# Generated by Django 6.0.1 on 2026-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_simpleuser_studentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_id', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=30)),
                ('ph_num', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('c_password', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('teacher_id', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=30)),
                ('ph_num', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('c_password', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='SimpleUser',
        ),
        migrations.DeleteModel(
            name='StudentRecord',
        ),
    ]
